#!/usr/bin/python

import shutil
import sys
import re
import os
import logging

logging.basicConfig(format='%(asctime)s:%(levelname)s: %(message)s', filename='/tmp/android-icon-move.log', level=logging.DEBUG, datefmt='%Y-%m-%d %H:%M:%S')

ANDROID_FOLDER_PREFIX='drawable-'

argumentCount = len(sys.argv)

for i in range(1,argumentCount):
    fileName = sys.argv[i]
    dirName = os.path.dirname(fileName)
    baseName = os.path.basename(fileName)
    logging.debug(dirName + ' + ' + baseName)

    # Find file type and prefix
    m = re.search('(.*)-(x*[hm]dpi).png', baseName)
    if m != None:
        filePrefix = m.group(1)
        fileRes = m.group(2)

        # Move file
        destDir = os.path.join(dirName, ANDROID_FOLDER_PREFIX + fileRes)
        destFile = os.path.join(destDir, filePrefix + '.png')
        if not os.path.exists(destDir):
            os.makedirs(destDir)

        if os.path.isdir(destDir):
            shutil.move(fileName, destFile)
