#!/bin/bash

DRIVE_DEFAULT=/dev/sdb1
KEY_FILE=/home/senth/ownCloud/configs/backup.key

if [ $# = 0 ]; then
	echo "Usage: $0 [mount|umount] [drive]"
elif [ "$1" = "mount" ]; then
	echo "Mounting backup"

	sudo cryptdisks_start backup && sudo mount /mnt/backup
elif [ "$1" = "umount" ]; then
	echo "Unmounting backup"

	sudo umount /mnt/backup && sudo cryptdisks_stop backup
else
	echo "Usage: $0 [mount|umount]"
fi
