#!/bin/bash
if [ $# -lt 2 ]; then
	echo "usage: captureCam [width] [height] [fps] [video-input] [output-file.avi]"
	echo "example: captureCam 640 480 30 /dev/video0 recording.avi"
	exit
fi

WIDTH=$1
HEIGHT=$2
FPS=$3
VIDEO=$4
OUT=$5

mencoder tv:// -tv driver=v4l2:width=$WIDTH:height=$HEIGHT:device=${VIDEO}:fps=$FPS:forceaudio:alsa:adevice=hw.0,0 -ovc lavc -lavcopts vcodec=mpeg4:vbitrate=1800 -ffourcc xvid -oac pcm -noskip -mc 0 -o $OUT
