#!/usr/bin/python

import os
import argparse
from subprocess import run


ICON_DIR = "/home/senth/.local/share/icons/hicolor/"

parser = argparse.ArgumentParser(description='Convert icon into app icons of all sizes.')
parser.add_argument('image', help='image to convert to app icons')
args = parser.parse_args()

for resolution in os.listdir(ICON_DIR):
    full_path = os.path.join(ICON_DIR, resolution)
    if (os.path.isdir(full_path)):
        dir_out = os.path.join(full_path, 'apps')
        file_out = os.path.join(dir_out, args.image)
        run(['convert', args.image, '-resize', resolution, file_out])

