#!/bin/bash

DIR="/home/senth/ownCloud/temp/encode_movies"
SARA_IN="sara"
SARA_OUT="${DIR}/encoded"
EMMA_IN="emma"
EMMA_OUT="${DIR}/Emma encoded movies"
VIDEOS_IN="videos"
VIDEOS_OUT="/home/senth/ownCloud/Camera Uploads/Videos"
DONE_OUT="${DIR}/original"

cd "$DIR"

# $1: movie file
# $2: out_dir
# $3: codec (default: libx264)
# $4: crf (default: 23)
encode_file() {
	local file=$1
	local out_dir=$2

	if [ -z "$3" ]; then
		local codec="libx264"
	else
		local codec=$3
	fi

	if [ -z "$4" ]; then
		local crf=23
	else
		local crf=$4
	fi

	if [ ! -e "$file" ]; then
		return
	fi

	ongoing_file="${file}.ongoing"
	# Skip ongoing files
	if [ ! -e "$ongoing_file" ]; then
		touch "$ongoing_file"

		filename="${file##*/}"
		filename="${filename%%.*}"
		outtemp="/tmp/$filename.mp4"
		outfile="$out_dir/$filename.mp4"

		ffmpeg -threads 8 -i "$file" -vcodec $codec -crf $crf "$outtemp"

		# Keep record date for file
		touch -r "$file" "$outtemp"

		# Cleanup
		mv "$outtemp" "$outfile"
		rm "$ongoing_file"
		mv "$file" "$DONE_OUT"
	fi
}

# Sara Movies
for file in $SARA_IN/*.mp4; do
	encode_file "$file" "$SARA_OUT"
done

# Camera Uploads
for file in $VIDEOS_IN/*.mp4; do
	encode_file "$file" "$VIDEOS_OUT"
done

# Emma Movies
for file in $EMMA_IN/*; do
	encode_file "$file" "$EMMA_OUT"
done