#!/bin/bash

server=$1
shift

FAC_CONFIG="/opt/factorio/.config/fac/config.ini"
FAC_EXEC="/opt/factorio/.local/bin/fac"
FACTORIO_HOME="/opt/factorio"
server_home="${FACTORIO_HOME}/${server}"

echo "[paths]" | sudo -u factorio tee "${FAC_CONFIG}" > /dev/null
echo "data-path = ${server_home}/data" | sudo -u factorio tee --append "${FAC_CONFIG}" > /dev/null
echo "write-path = ${server_home}" | sudo -u factorio tee --append "${FAC_CONFIG}" > /dev/null

sudo -u factorio "${FAC_EXEC}" "$@"
