#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Not the right amount of parameters (one), please specify the first part of the ip-address. E.g. find_all_workstations 192.168.0"
	exit
fi

ip_begin=$1

up_stations=""

for ip in $(seq 1 254); do
	ping -c 1 -W 1 "$ip_begin.$ip">/dev/null
	if [ $? -eq 0 ]; then
		echo "$ip_begin.$ip UP"
		up_stations="$up_stations \\ $ip_begin.$ip"
	else
		echo "$ip_begin.$ip DOWN"
	fi
done

echo "$up_stations"
