#!/bin/bash

# Get master/main branch name
master_test=`git branch | sed 's/ *//' | grep master`
main_test=`git branch | sed 's/ *//' | grep main`

if [ "$master_test" = "master" ]; then
  base_branch="master"
elif [ "$main_test" = "main" ]; then
  base_branch="main"
elif [ "$master_test" = "* master" ]; then
  echo "Already on master branch, can't rebase from master"
  exit 0
elif [ "$main_test" = "* main" ]; then
  echo "Already on main branch, can't rebase into main"
  exit 0
else
  echo "Didn't find master or main branch"
  exit 1
fi

echo "Base branch: $base_branch"

# Get current branch
current_branch=`git branch | grep '*'`
current_branch=${current_branch/\* /}

echo "Current branch: $current_branch"


git checkout "$base_branch"
git pull
git checkout "$current_branch"
git rebase "$base_branch"

echo ""
echo "Done rebasing!"
