#!/usr/bin/python3

import argparse
import os
from pathlib import Path

src_hook_dir = Path("/home/senth/.commands/git-hooks")
git_hook_dir = Path(".git/hooks")

hooks = {"pre-commit-go": "pre-commit"}

available_hook_names = []
for hook_name in hooks:
    available_hook_names.append(hook_name)

parser = argparse.ArgumentParser(help="Installs git hooks")
parser.add_argument("hook", choices=available_hook_names, help="The hook to install")

args = parser.parse_args()

# Symlink commit
hook_name = args.hook
hook_type = hooks[hook_name]

hook_src_file = src_hook_dir.joinpath(hook_name)
hooks_symlink_file = git_hook_dir.joinpath(hook_type)
os.symlink(hook_src_file, hooks_symlink_file)
