#!/bin/bash

# Script for cloning github repositories

# Use senth as repository
if [ $# -eq 1 ]; then
  git clone git@github.com:Senth/$1.git
# Custom username
elif [ $# -eq 2 ]; then
  git clone git@github.com:$1/$2.git
else
  echo "From Senth: $0 repo-name"
  echo "From user: $0 username repo-name"
fi