#!/bin/bash
if [[ $# < 2 ]]; then
	echo "Usage: lowerpitch [infile] [outfile]"
	exit;
fi

IN_FILE=$1
OUT_FILE=$2

# Get the extension
EXT_IN=${IN_FILE##*.}
EXT_OUT=${OUT_FILE##*.}

# Temporary files
TMP_IN_FILE=".tmp_file.$EXT_IN"
TMP_OUT_FILE=".tmp_file.$EXT_OUT"
WAVE_FILE=".tmp_wave.wav"
LOW_PITCH_WAVE=".tmp_low_pitch.wav"

# copy file so that it doesn't contain any spaces
cp $IN_FILE $TMP_IN_FILE

# convert to a wave file
ffmpeg -y -i -threads 4 $TMP_IN_FILE $WAVE_FILE

# lower the pitch
rubberband --pitch -1 --threads $WAVE_FILE $LOW_PTICH_WAVE

# convert it to the new type
ffmpeg -y -i -threads 4 $LOW_PITCH_WAVE $TMP_OUT_FILE

# move the temp file to the out file
mv $TMP_OUT_FILE $OUT_FILE

# Delete temporary files
rm $WAVE_FILE $LOW_PITCH_WAVE $TMP_IN_FILE

echo 'Done!'
