#!/usr/bin/python3

import argparse
import configparser
from pathlib import Path
from subprocess import run
from sys import exit
from typing import Any, Union

HOME_DIR = Path.home()
CONFIG_FILE = HOME_DIR.joinpath(".owncloud-sync-config")
EXCLUDE_FILE = HOME_DIR.joinpath(".owncloud-exclude-list")
OWNCLOUD_DIR = HOME_DIR.joinpath("ownCloud")
OWNCLOUD_URL = "https://owncloud.senth.org"

parser = argparse.ArgumentParser()
parser.add_argument("-s", "--silent", help="No output")
args = parser.parse_args()


class Config:
    def __init__(self) -> None:
        self.silent: str = args.silent
        self.user: Union[str, None] = None
        self.password: Union[str, None] = None
        self._set_from_config_file()

    def _set_from_config_file(self) -> None:
        if not CONFIG_FILE.exists():
            return

        config = configparser.ConfigParser()
        config.read(CONFIG_FILE)

        # Login
        if "Login" in config:
            login_config = config["Login"]
            self.user = self._read_from_config(login_config, "User")
            self.password = self._read_from_config(login_config, "Password")

    def _read_from_config(self, config: configparser.SectionProxy, varname: str) -> Any:
        if varname in config:
            return config[varname]
        if varname.lower() in config:
            return config[varname]

    def validate(self) -> None:
        if not self.user:
            print("No user has been set in either the config file or argument")
            exit(1)
        if not self.password:
            print("No password has been set in either the config file or argument")
            exit(1)


config = Config()
config.validate()

command = [
    "owncloudcmd",
    "-h",
    "--non-interactive",
    "-u",
    config.user,
    "-p",
    config.password,
]

if config.silent:
    command.append("-s")

if EXCLUDE_FILE.exists():
    command.append("--exclude")
    command.append(EXCLUDE_FILE)

command.append(OWNCLOUD_DIR)
command.append(OWNCLOUD_URL)

print(command)
run(command)
