#!/usr/bin/python3

import os
from pathlib import Path

patch_files = {
    "keymap.xml": Path("keymaps") / "Senth.xml",
    "Scratchpad.xml": Path("Scratchpad.xml"),
}
nextcloud_dir = Path.home() / "nextcloud" / "configs" / "JetBrains"
jetbrains_dir = Path.home() / ".config" / "JetBrains"

# Special case for Windows
if os.name == "nt":
    jetbrains_dir = Path.home() / "AppData" / "Roaming" / "JetBrains"

valid_ide_dir_starts_with = [
    "GoLand",
    "IdeaIC",
    "JetBrainsClient",
]

# Iterate over all Jetbrains IDE directories and check if the keymap file exists
for ide_dir in jetbrains_dir.iterdir():
    if not ide_dir.is_dir():
        continue

    if not any([ide_dir.name.startswith(x) for x in valid_ide_dir_starts_with]):
        continue

    # Iterate over all patch files and add them
    for in_file, out_file in patch_files.items():
        nextcloud_file = nextcloud_dir / in_file
        ide_file = ide_dir / out_file

        # Create dir if it doesn't exist
        ide_file.parent.mkdir(parents=True, exist_ok=True)

        # Remove existing symlink
        ide_file.unlink(missing_ok=True)

        # Create symlink
        ide_file.symlink_to(nextcloud_file)
