#!/bin/bash
VENV_DIR="$HOME/.venvs/$(basename $1)"
command="$1"
shift

if [ ! -d "$VENV_DIR" ]; then
	python3 -m venv "$VENV_DIR"
	source "$VENV_DIR/bin/activate"
	pip install -r "$command.requirements.txt"
	# copy requirements so that we can check if there's any diff
	cp "$command.requirements.txt" "$VENV_DIR/requirements.txt"
else
	source "$VENV_DIR/bin/activate"
	diff "$command.requirements.txt" "$VENV_DIR/requirements.txt" > /dev/null
	if [ $? -ne 0 ]; then
		echo "Requirements have changed. Reinstalling..."
		pip install -r "$command.requirements.txt"
		cp "$command.requirements.txt" "$VENV_DIR/requirements.txt"
	fi
fi

python3 "$command" "$@"
