#!/usr/bin/python3

import glob
import re
import datetime
import os

regexPattern = re.compile("[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])")

for filename in glob.iglob("*"):
    dateMatch = re.search(regexPattern, filename)
    if dateMatch is not None:
        date = dateMatch.group(0)
        posixTime = int(datetime.datetime.strptime(date, "%Y-%m-%d").timestamp())
        os.utime(filename, (posixTime, posixTime))
