#!/bin/bash

COUNTER=0
SECONDS_BEFORE_SHUTDOWN=60
LOAD_THRESHOLD=4

while [ $COUNTER -le $SECONDS_BEFORE_SHUTDOWN ]; do
	CURRENT_LOAD=`top -b -n1 -d3 | grep root | head -n 1 | cut -c44-45`
	
	if [ $CURRENT_LOAD -le $LOAD_THRESHOLD ]; then
		let COUNTER=COUNTER+1
		echo "Low load ($CURRENT_LOAD) in $COUNTER seconds..."
	# Always reset the counter if the load goes up
	else
		let COUNTER=0
	fi
	sleep 1
done

# Run shutdown script
shutdown -h now
