#!/bin/bash

SECONDS_BEFORE_SHUTDOWN=90
counter=$SECONDS_BEFORE_SHUTDOWN
LOAD_THRESHOLD=6

while [ $counter -ge 0 ]; do
	# Using ps
	current_load=`ps -eo pcpu | sort -k 1 -r | head -1 | cut -c1-2`

	# If start with %C use second row instead
	if [ "$current_load" = "%C" ]; then
		current_load=`ps -eo pcpu | sort -k 1 -r | head -2 | tail -1 | cut -c1-2`
	fi

	# First letter is space -> remove it
	first_letter=${current_load:0:1}
	if [ "$first_letter" = " " ]; then
		current_load=${current_load:1:1}
	fi
	
	if [ $current_load -le $LOAD_THRESHOLD ]; then
		let counter=counter-1
		echo "Low load ($current_load%). Shutdown in $counter seconds..."
	# Always reset the counter if the load goes up
	else
		let counter=$SECONDS_BEFORE_SHUTDOWN
	fi
	sleep 1
done

# Either shutdown or sleep
if [ "$1" = "sleep" ]; then 
	qdbus --system "org.freedesktop.UPower" "/org/freedesktop/UPower" org.freedesktop.UPower.Suspend
# Run shutdown script
else
	qdbus "org.kde.ksmserver" /KSMServer logout 0 2 2
fi
