#!/bin/bash

SLEEP_5MIN=300
SLEEP_1MIN=60
MESSAGE_TIME=10

if [ $# -lt 1 ]; then
	echo "Not enough parameters"
	echo "Usage: shutdown_15min ENVIRONMENT (kde | gnome | system)"
	exit
fi
ENVIRONMENT=$1


# Commands, and environmental stuff
if [ "$ENVIRONMENT" = "kde" ]; then
	export KDE_FULL_SESSION=true
	export KDE_SESSION_UID=1001
	export KDE_SESSION_VERSION=4
	export DISPLAY=:0.0

	# Export dbus
	DBUS_PID=`pgrep -u $USER startkde`
	export $(cat /proc/${DBUS_PID}/environ | tr \\0 \\n | grep -E '^DBUS_SESSION_BUS_ADDRESS=')

	# Create the messaging variable
	MESSAGE_COMMAND_BEGIN="/usr/bin/kdialog --passivepopup"
	MESSAGE_COMMEND_END=$MESSAGE_TIME

	SHUTDOWN_COMMAND="DISPLAY=$DISPLAY /usr/bin/qdbus org.kde.ksmserver /KSMServer logout 0 2 2"
elif [ "$ENVIRONMENT" = "gnome" ]; then
	# TODO
	MESSAGE_COMMAND_BEGIN=""
	MESSAGE_COMMAND_END=""

	SHUTDOWN_COMMAND=""
	echo "Gnome functionality has not been implemented yet!"
	exit
elif [ "$ENVIRONMENT" = "system" ]; then
	MESSAGE_COMMAND_BEGIN="echo"
	MESSAGE_COMMAND_END=""

	SHUTDOWN_COMMAND="shutdown -h now"
fi

# Show first message for 1 minute
if [ "$ENVIRONMENT" = "kde" ]; then
	$MESSAGE_COMMAND_BEGIN "System is going to shutdown in 15 minutes, save all documents!" 60
	kdialog --msgbox "System is going down in 15 minutes, save all documents!"
fi

# Sleep 5 minutes then display a passive popup (10min left)
sleep $SLEEP_5MIN
$MESSAGE_COMMAND_BEGIN "10 minutes until system shuts down..." $MESSAGE_COMMAND_END

# Sleep for another 5 minutes then start to display a passive popup each minute
sleep $SLEEP_5MIN
minutes_left=5
until [ $minutes_left -le 1 ]; do
	$MESSAGE_COMMAND_BEGIN "$minutes_left minutes until system shuts down..." $MESSAGE_COMMEND_END
	let minutes_left=minutes_left-1
	sleep $SLEEP_1MIN
done

# This should be 1 minute left
$MESSAGE_COMMAND_BEGIN "$minutes_left minutes until system shuts down..." $MESSAGE_COMMEND_END

# Popup when 30 seconds left
sleep 30
$MESSAGE_COMMAND_BEGIN "30 seconds until system shuts down..." $MESSAGE_COMMAND_END

# Popup 10 seconds left
sleep 20
$MESSAGE_COMMAND_BEGIN "10 seconds until system shuts down..." $MESSAGE_COMMEND_END

# Shutdown the system
sleep 10
eval $SHUTDOWN_COMMAND
