#!/bin/bash
if command -v apt-get &> /dev/null; then
	sudo apt-get update
	sudo apt-get upgrade -y
fi

# Brew
if command -v brew &> /dev/null; then
	brew upgrade
fi

# Golang
if command -v go &> /dev/null; then
	/home/senth/.commands/update-golang
fi

# Nodejs
if command -v node &> /dev/null; then
  curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
	sudo apt-get install -y nodejs
fi
