#!/bin/bash

BLOCKER=$1
BLOCKED=$2

if [[ "$BLOCKED" == "" ]]; then
 echo "unblock <blocker> <blocked>"
  exit;
  fi

sudo  emerge --buildpkgonly --nodeps $BLOCKED && sudo emerge -C $BLOCKER && sudo emerge --usepkgonly $BLOCKED
