#!/bin/bash

source /etc/conf.d/factorio

if [ $# != 1 ]; then
	echo "Please pass a version number"
	exit
fi
version=$1

# Save current dir
cur_dir="$PWD"

# Stop factorio
sudo /etc/init.d/factorio stop

# Download factorio
UPDATE_NAME=factorio-$version.tar
update_tar=/tmp/$UPDATE_NAME
wget -O "$update_tar" "https://factorio.com/get-download/$version/headless/linux64"

# Update all servers
for i in "${!SERVERS[@]}"; do
	server="${SERVERS[$i]}"
	server_full="$FACTORIO_HOME/$server"
	sudo tar xvf "$update_tar" --strip-components=1 -C "$server_full"
	sudo chown factorio:factorio -R "$server_full"
done

# Start factorio
sudo /etc/init.d/factorio start

# Remove downloaded file
rm "$update_tar"

cd "$cur_dir"
