#!/bin/bash
if [[ $# < 2 ]]; then
	echo "Usage: youtube2mp3 [youtube-url] [mp3-path]"
	exit
fi

URL="$1"
OUT_FILE="$2"

# Download best quality, start with the best format, if not available
# download next format

temp_file=youtube-dl-$RANDOM-$RANDOM.mp4.webm
yt-dlp --output=$temp_file --audio-format best "$URL"
if [ -f "$temp_file" ]; then
	# Create mp3 file
	ffmpeg -i $temp_file -acodec libmp3lame -ac 2 -ab 320k -vn -y "$OUT_FILE"
	rm $temp_file
fi
